apiVersion: v1
kind: PersistentVolume
metadata:
  name: settings-db-volume
  labels:
    type: local
    app: settings-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
