apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: settings-db-pv-claim
  labels:
    app: settings-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi